# Generated by Django 2.2.6 on 2019-10-06 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def create_default_resumes(apps, schema_editor):
        users = apps.get_model('auth', 'user')

        for user in users.objects.all():
            resume = apps.get_model('resume', 'Resume')()
            resume.id = user.id
            resume.name = "Default Resume"
            resume.user_id = user.id
            resume.save()

        resumeItems = apps.get_model('resume', 'ResumeItem')

        for resumeItem in resumeItems.objects.all():
            resumeItem.Resume_id = resumeItem.user_id
            resumeItem.save()

    def delete_resumes(apps, schema_editor):
        resumes = apps.get_model('resume', 'Resume')
        for resume in resumes.objects.all():
            resume.delete()

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ]),
        migrations.AddField(
            model_name="ResumeItem",
            name="Resume",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="resume.Resume",
            ),
        ),
        migrations.RunPython(create_default_resumes, delete_resumes),
        migrations.AlterField(
            model_name="ResumeItem",
            name="Resume",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="resume.Resume",
            ),
        ),
        migrations.AlterField(
            model_name='ResumeItem',
            name='user_id',
            field=models.ForeignKey(to='auth.User', db_constraint=False, db_index=True, null=False,
                                    on_delete=models.PROTECT)
        ),
        migrations.RemoveField(
            model_name="ResumeItem",
            name="user",
        )
    ]
